# Generated by Django 5.2.4 on 2025-07-18 23:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_visita', models.TextField()),
                ('sendero_visitado', models.TextField()),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sendero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sendero', models.CharField(max_length=50)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dificultad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', api.models.CampoEncriptado(max_length=255)),
                ('nombre', api.models.CampoEncriptado(max_length=255)),
                ('apellido', api.models.CampoEncriptado(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_pasaporte', api.models.CampoEncriptado(max_length=255)),
                ('nombre_visitante', api.models.CampoEncriptado(max_length=255)),
                ('nacionalidad', api.models.CampoEncriptado(max_length=255)),
                ('adulto_nino', models.CharField(max_length=255)),
                ('telefono', api.models.CampoEncriptado(max_length=255)),
                ('genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.JSONField()),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrovisita')),
            ],
        ),
        migrations.CreateModel(
            name='SenderoFoto',
            fields=[
                ('id_sendero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sendero')),
                ('ref_foto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField()),
                ('valoracion', models.PositiveSmallIntegerField()),
                ('sendero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sendero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='registrovisita',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visitante'),
        ),
    ]
