# Generated by Django 5.2.4 on 2025-07-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registrovisita_hora_entrada_alter_usuario_email'),
        ('api', '0003_alter_visitante_cedula_pasaporte'),
    ]

    operations = [
    ]
